<?php

namespace App\Database\Seeds;

use App\Models\EmpleadoModel;
use CodeIgniter\Database\Seeder;

class EmpleadosSeeder extends Seeder
{
    public function run()
    {
        $empleado= new EmpleadoModel();
        $data = [
            [
                'legajo' => 1001, 
                'nombre' => 'Juan', 
                'apellido' => 'Pérez', 
                'dni' => 30543210, 
                'fechaNacimiento' => '1985-05-10', 
                'gmail' => 'juan.perez@gmail.com', 
                'telefono' => '1123456789', 
                'sector' => 'Medicina', 
                'rol' => 'Admin. Medicina Laboral',
                'contrasenia' => 'AdminJuan1',
            ],
            [
                'legajo' => 1002, 
                'nombre' => 'María', 
                'apellido' => 'Gómez', 
                'dni' => 28564321, 
                'fechaNacimiento' => '1987-07-14', 
                'gmail' => 'maria.gomez@gmail.com', 
                'telefono' => '1123456790', 
                'sector' => 'Medicina', 
                'rol' => 'Admin. Medicina Laboral',
                'contrasenia' => 'admin11',
            ],
            [
                'legajo' => 1003, 
                'nombre' => 'Carlos', 
                'apellido' => 'López', 
                'dni' => 29564123, 
                'fechaNacimiento' => '1990-03-25', 
                'gmail' => 'carlos.lopez@gmail.com', 
                'telefono' => '1123456791', 
                'sector' => 'Medicina', 
                'rol' => 'Admin. Medicina Laboral',
                'contrasenia' => '',
            ],
            [
                'legajo' => 1004, 
                'nombre' => 'Ana', 
                'apellido' => 'Martínez', 
                'dni' => 31564234, 
                'fechaNacimiento' => '1992-08-30', 
                'gmail' => 'ana.martinez@gmail.com', 
                'telefono' => '1123456792', 
                'sector' => 'Recursos Humanos', 
                'rol' => 'Empleado Común',
                'contrasenia' => 'Ana12345',
            ],
            [
                'legajo' => 1005, 
                'nombre' => 'Luis', 
                'apellido' => 'Rodríguez', 
                'dni' => 32564321, 
                'fechaNacimiento' => '1988-01-20', 
                'gmail' => 'luis.rodriguez@gmail.com', 
                'telefono' => '1123456793', 
                'sector' => 'Logística', 
                'rol' => 'Empleado Común',
                'contrasenia' => 'Luis1005',
            ],
            [
                'legajo' => 1006, 
                'nombre' => 'Laura', 
                'apellido' => 'Fernández', 
                'dni' => 27563212, 
                'fechaNacimiento' => '1995-09-12', 
                'gmail' => 'laura.fernandez@gmail.com', 
                'telefono' => '1123456794', 
                'sector' => 'Finanzas', 
                'rol' => 'Empleado Común',
                'contrasenia' => '',
            ],
            [
                'legajo' => 1007, 
                'nombre' => 'Diego', 
                'apellido' => 'Silva', 
                'dni' => 33564321, 
                'fechaNacimiento' => '1989-11-15', 
                'gmail' => 'diego.silva@gmail.com', 
                'telefono' => '1123456795', 
                'sector' => 'Ventas', 
                'rol' => 'Empleado Común',
                'contrasenia' => '1234',
            ],
            [
                'legajo' => 1008, 
                'nombre' => 'Clara', 
                'apellido' => 'Castro', 
                'dni' => 34564322, 
                'fechaNacimiento' => '1991-03-07', 
                'gmail' => 'clara.castro@gmail.com', 
                'telefono' => '1123456796', 
                'sector' => 'Administración', 
                'rol' => 'Empleado Común',
                'contrasenia' => '',
            ],
            [
                'legajo' => 1009, 
                'nombre' => 'Martín', 
                'apellido' => 'García', 
                'dni' => 35564323, 
                'fechaNacimiento' => '1986-06-25', 
                'gmail' => 'martin.garcia@gmail.com', 
                'telefono' => '1123456797', 
                'sector' => 'Producción', 
                'rol' => 'Empleado Común',
                'contrasenia' => '',
            ],
            [
                'legajo' => 1010, 
                'nombre' => 'Sofía', 
                'apellido' => 'Mendoza', 
                'dni' => 36564324, 
                'fechaNacimiento' => '1993-02-12', 
                'gmail' => 'sofia.mendoza@gmail.com', 
                'telefono' => '1123456798', 
                'sector' => 'Finanzas', 
                'rol' => 'Empleado Común',
                'contrasenia' => '',
            ],
            [
                'legajo' => 1011, 
                'nombre' => 'Javier', 
                'apellido' => 'Ramírez', 
                'dni' => 37564325, 
                'fechaNacimiento' => '1990-10-05', 
                'gmail' => 'javier.ramirez@gmail.com', 
                'telefono' => '1123456799', 
                'sector' => 'Administración', 
                'rol' => 'Empleado Común',
                'contrasenia' => '',
            ],
            [
                'legajo' => 1012, 
                'nombre' => 'Florencia', 
                'apellido' => 'Ríos', 
                'dni' => 38564326, 
                'fechaNacimiento' => '1987-04-20', 
                'gmail' => 'florencia.rios@gmail.com', 
                'telefono' => '1123456700', 
                'sector' => 'Logística', 
                'rol' => 'Empleado Común',
                'contrasenia' => '',
            ],
            [
                'legajo' => 1013, 
                'nombre' => 'Federico', 
                'apellido' => 'Díaz', 
                'dni' => 39564327, 
                'fechaNacimiento' => '1994-01-28', 
                'gmail' => 'federico.diaz@gmail.com', 
                'telefono' => '1123456701', 
                'sector' => 'Recursos Humanos', 
                'rol' => 'Empleado Común',
                'contrasenia' => '',
            ],
            [
                'legajo' => 1014, 
                'nombre' => 'Verónica', 
                'apellido' => 'Morales', 
                'dni' => 40564328, 
                'fechaNacimiento' => '1986-08-15', 
                'gmail' => 'veronica.morales@gmail.com', 
                'telefono' => '1123456702', 
                'sector' => 'Producción', 
                'rol' => 'Empleado Común',
                'contrasenia' => '',
            ],
            [
                'legajo' => 1015, 
                'nombre' => 'Ignacio', 
                'apellido' => 'Torres', 
                'dni' => 41564329, 
                'fechaNacimiento' => '1989-09-02', 
                'gmail' => 'ignacio.torres@gmail.com', 
                'telefono' => '1123456703', 
                'sector' => 'Finanzas', 
                'rol' => 'Empleado Común',
                'contrasenia' => '',
            ],
            [
                'legajo' => 1016, 
                'nombre' => 'Romina', 
                'apellido' => 'Vega', 
                'dni' => 42564330, 
                'fechaNacimiento' => '1992-12-19', 
                'gmail' => 'romina.vega@gmail.com', 
                'telefono' => '1123456704', 
                'sector' => 'Ventas', 
                'rol' => 'Empleado Común',
                'contrasenia' => '',
            ],
            [
                'legajo' => 1017, 
                'nombre' => 'Fernando', 
                'apellido' => 'Medina', 
                'dni' => 43564331, 
                'fechaNacimiento' => '1991-06-10', 
                'gmail' => 'fernando.medina@gmail.com', 
                'telefono' => '1123456705', 
                'sector' => 'Recursos Humanos', 
                'rol' => 'Empleado Común',
                'contrasenia' => '',
            ],
            [
                'legajo' => 1018, 
                'nombre' => 'Julia', 
                'apellido' => 'Sánchez', 
                'dni' => 44564332, 
                'fechaNacimiento' => '1988-03-14', 
                'gmail' => 'julia.sanchez@gmail.com', 
                'telefono' => '1123456706', 
                'sector' => 'Producción', 
                'rol' => 'Empleado Común',
                'contrasenia' => '',
            ],
            [
                'legajo' => 1019, 
                'nombre' => 'Sebastián', 
                'apellido' => 'Molina', 
                'dni' => 45564333, 
                'fechaNacimiento' => '1990-11-30', 
                'gmail' => 'sebastian.molina@gmail.com', 
                'telefono' => '1123456707', 
                'sector' => 'Logística', 
                'rol' => 'Empleado Común',
                'contrasenia' => '',
            ],
            [
                'legajo' => 1020, 
                'nombre' => 'Valentina', 
                'apellido' => 'Acosta', 
                'dni' => 46564334, 
                'fechaNacimiento' => '1991-07-22', 
                'gmail' => 'valentina.acosta@gmail.com', 
                'telefono' => '1123456708', 
                'sector' => 'Finanzas', 
                'rol' => 'Empleado Común',
                'contrasenia' => '',
            ],
            [
                'legajo' => 1021,
                'nombre' => 'Santiago',
                'apellido' => 'Cabrera',
                'dni' => 47564335,
                'fechaNacimiento' => '1989-11-25',
                'gmail' => 'santiago.cabrera@gmail.com',
                'telefono' => '1123456709',
                'sector' => 'Recursos Humanos',
                'rol' => 'Empleado Común',
                'contrasenia' => '',
            ],
            [
                'legajo' => 1022,
                'nombre' => 'Agustina',
                'apellido' => 'Villalba',
                'dni' => 48564336,
                'fechaNacimiento' => '1990-05-18',
                'gmail' => 'agustina.villalba@gmail.com',
                'telefono' => '1123456710',
                'sector' => 'Administración',
                'rol' => 'Empleado Común',
                'contrasenia' => '',
            ],
            [
                'legajo' => 1023,
                'nombre' => 'Matías',
                'apellido' => 'Correa',
                'dni' => 49564337,
                'fechaNacimiento' => '1995-04-05',
                'gmail' => 'matias.correa@gmail.com',
                'telefono' => '1123456711',
                'sector' => 'Producción',
                'rol' => 'Empleado Común',
                'contrasenia' => '',
            ],
            [
                'legajo' => 1024,
                'nombre' => 'Andrea',
                'apellido' => 'Ponce',
                'dni' => 50564338,
                'fechaNacimiento' => '1992-12-10',
                'gmail' => 'andrea.ponce@gmail.com',
                'telefono' => '1123456712',
                'sector' => 'Ventas',
                'rol' => 'Empleado Común',
                'contrasenia' => '',
            ],
            [
                'legajo' => 1025,
                'nombre' => 'Lucas',
                'apellido' => 'Meza',
                'dni' => 51564339,
                'fechaNacimiento' => '1988-09-18',
                'gmail' => 'lucas.meza@gmail.com',
                'telefono' => '1123456713',
                'sector' => 'Producción',
                'rol' => 'Empleado Común',
                'contrasenia' => '10251025Aa',
            ],
            [
                'legajo' => 1026,
                'nombre' => 'Paula',
                'apellido' => 'Riquelme',
                'dni' => 52564340,
                'fechaNacimiento' => '1993-06-22',
                'gmail' => 'paula.riquelme@gmail.com',
                'telefono' => '1123456714',
                'sector' => 'Finanzas',
                'rol' => 'Empleado Común',
                'contrasenia' => '',
            ],
            [
                'legajo' => 1027,
                'nombre' => 'Diego',
                'apellido' => 'Vargas',
                'dni' => 53564341,
                'fechaNacimiento' => '1990-08-11',
                'gmail' => 'diego.vargas@gmail.com',
                'telefono' => '1123456715',
                'sector' => 'Sistemas',
                'rol' => 'Empleado Común',
                'contrasenia' => '',
            ],
            [
                'legajo' => 1028,
                'nombre' => 'Jazmín',
                'apellido' => 'Sosa',
                'dni' => 54564342,
                'fechaNacimiento' => '1994-03-30',
                'gmail' => 'jazmin.sosa@gmail.com',
                'telefono' => '1123456716',
                'sector' => 'Administración',
                'rol' => 'Empleado Común',
                'contrasenia' => '',
            ],
            [
                'legajo' => 1029,
                'nombre' => 'Hernán',
                'apellido' => 'Romero',
                'dni' => 55564343,
                'fechaNacimiento' => '1991-01-03',
                'gmail' => 'hernan.romero@gmail.com',
                'telefono' => '1123456717',
                'sector' => 'Sistemas',
                'rol' => 'Empleado Común',
                'contrasenia' => '',
            ],
            [
                'legajo' => 1030,
                'nombre' => 'Valeria',
                'apellido' => 'Navarro',
                'dni' => 56564344,
                'fechaNacimiento' => '1992-05-25',
                'gmail' => 'valeria.navarro@gmail.com',
                'telefono' => '1123456718',
                'sector' => 'Logística',
                'rol' => 'Empleado Común',
                'contrasenia' => '',
            ],
            [
                'legajo' => 1031,
                'nombre' => 'Luciana',
                'apellido' => 'Perez',
                'dni' => 46372819,
                'fechaNacimiento' => '2000-04-21',
                'gmail' => 'luciana.perez@gmail.com',
                'telefono' => '1123456718',
                'sector' => 'Ventas',
                'rol' => 'Empleado Común',
                'contrasenia' => '',
            ]
        ];
        $data= $empleado->hashPassword($data);
        $empleado->insertBatch($data);
    }
}
